### ISSUE TITLE
Remove blue outline when selecting according (+) and (-) buttons

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#12]
<img width="687" alt="Screen Shot 2020-12-06 at 6 57 30 PM" src="https://user-images.githubusercontent.com/75499962/101297104-2871e480-37f5-11eb-84ea-6e820268ce94.png">

**Comment by rudietuesdays** [comment]
@jennwlow so this is actually an accessibility feature; the outline appears for users who use keyboard navigation so they know what element they're focused on. It's definitely ugly in this case, thanks for catching that! Though it wouldn't be great for accessibility to remove it entirely, it can be styled differently. I changed the style a bit to be more consistent with the site design -- please let me know what you think and if you have further questions about this! If it's all good, feel free to close this issue.

**Comment by jennwlow** [comment]
Ahhh, that makes sense. The new styling is good, thank you for adjusting!
