### ISSUE TITLE
Map: Friendship Arch location is located at the intersection of H Street & 7th Street

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#15]
It looks like the pin is near the Carnegie Library right now.

**Comment by rudietuesdays** [comment]
updated along with #14, please close if good @jennwlow !

**Comment by jennwlow** [comment]
Cool -- I noticed that I don't see anything on the map anymore. I assume its because the color coding is in process?

**Comment by rudietuesdays** [comment]
Thanks for catching! It was actually an issue with a slight change in the url to the geocoding API, which is now fixed. You may need to do a hard refresh, but they should be showing up now. Lmk if you're still not seeing them though!

**Comment by rudietuesdays** [comment]
Also as a heads up @jennwlow, the building colors have been really finicky so I've temporarily changed the color of the markers to match the color of the category as an interim fix. I wanted to make sure it's ready to go live even if this needs a bit more work, but lmk if this is ok in the meantime!

**Comment by jennwlow** [comment]
Yes, that's totally fine @rudietuesdays thanks for letting me know.

Okay, I now see the different colored circles and triangles, yay! Not all of them but probably half of them right now:
![Screen Shot 2021-01-11 at 6 18 00 PM](https://user-images.githubusercontent.com/75499962/104249437-650aae80-5439-11eb-9911-712ae97f3c1e.png)

**Comment by rudietuesdays** [comment]
@jennwlow so right now the number of them that you see depends on where you've scrolled on the map and what zoom level you're at, since if all of them display always, it gets pretty crowded. I can change it to display that way so you can see what I mean if you'd like! Let me know.

**Comment by rudietuesdays** [comment]
If it's helpful as a follow up, here's a zoomed in screenshot:
<img width="1330" alt="Screen Shot 2021-01-30 at 12 07 30 PM" src="https://user-images.githubusercontent.com/10843135/106362986-cbc21000-62f3-11eb-95b3-35c27351b461.png">

**Comment by jennwlow** [comment]
I see that now, thanks for the clarification. Once we confirm how the map features work I'm going to add a couple of additional sentences to the map page's intro to let visitors know to zoom in to discover more mapped locations.

**Comment by rudietuesdays** [comment]
Sounds good! Let me know when you have the updated language and I'll add it in.
