### ISSUE TITLE
Map Legend: Grocery Store Name Correction

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#16]
"Dat Teong Grocery" should actually be "Tuchkcheong Company".

**Comment by rudietuesdays** [comment]
updated, please close if good @jennwlow !

I also added you to the AirTable base where you can change data like this :) let me know if you don't receive the invite email or have trouble with the link!

**Comment by jennwlow** [comment]
Looks good and received the Airtable invite! I added some more grocery stores from an interview I had last month.
