### ISSUE TITLE
Intro text at the top of home page

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#2]
Increase introduction text at the top of the home page size to be approx (or exactly) the same as the "About the Project" headers.

**Comment by rudietuesdays** [comment]
@jennwlow updated, let me know what you think! If it looks good feel free to close this issue, otherwise let me know how you'd like it tweaked.

**Comment by jennwlow** [comment]
The size looks great! Is it just me or does the top of the first line of text look like it's cut off slightly?
![Screen Shot 2020-12-23 at 11 37 50 AM](https://user-images.githubusercontent.com/75499962/103018647-987dab80-4513-11eb-95e2-165051866818.png)

**Comment by rudietuesdays** [comment]
@jennwlow ah yes, great catch! Let me know if it looks better now.

**Comment by jennwlow** [comment]
Perfect, thanks!
