### ISSUE TITLE
Text Update: Chinatown Voices Page

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#24]
We want to hear from more voices from the neighborhood.

Please help us by contributing your stories and memories about cherished places in Washington, D.C.'s Chinatown, past and present. Your stories will help us make the case for preserving, protecting, and sustaining the cultural, social, spiritual, and physical health of the neighborhood.

Call for Oral Histories

Do you have photos and memories to share? Please contact us at info@dearchinatowndc.org (Please highlight the email ID in a different color on the website) if you (or a family member) is interested in sharing their own history and personal experiences relating to Washington, D.C.'s Chinatown. We'd be delighted to host a short conversation or conduct your own oral history interview (virtual or in-person with proper safety precautions) and provide you with a copy of all of the interview materials produced (audio recording and written transcript) for your family's records.

Help Us Build the Map

Do you know of a place in the neighborhood that is not highlighted in the Chinatown Map **(add hyperlink here)** but should be? Email us at info@dearchinatowndc.org **(highlight the email ID in a different color on the website)** and include your name, the name of the location, the address (or approximate location), whether it is still in the neighborhood or not, and one to two sentences about why this place holds a special place in your memory.

**Comment by rudietuesdays** [comment]
updated along with #25, please close if good @jennwlow !
