### ISSUE TITLE
Text Update: Chinatown Connects

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#25]
D.C.’s Chinatown’s both visibility and invisibility makes for a unique case study. Its relatively small footprint within the city’s center has transformed dramatically over the past forty years. Furthermore, D.C.’s Chinatown rarely makes it into the public dialogue amongst larger, and more well-known Chinatowns across the continent, despite being marked by similar patterns of gentrification and erasure, albeit at a smaller scale in comparison to San Francisco, New York City, or Boston. 

However, we understand that this issue is bigger than Washington D.C.'s Chinatown.

This project aims to be in conversation with the issues of equity, affordability, and cultural erasure in Chinatowns across the continent and is in solidarity with neighborhoods across Washington, D.C., particularly in Black and Brown neighborhoods that are bearing a disproportionate burden from displacement and cultural erasure as a result of gentrification across the District.

We encourage you to check out other mapping projects that we continue to learn from and be inspired by that also amplify longtime community voices and perspectives and what they treasure about their neighborhoods: 

[Love Letters to Chinatown](https://erinreiss.github.io/wowmap/?mc_cid=8c994074bf&mc_eid=895ec35150) by the W.O.W. Project, New York City
[Takachizu](http://www.takachizu.org/) by Little Tokyo Service Center, Los Angeles
[Your Story, Our Story](https://yourstory.tenement.org/) by the Tenement Museum, New York City
[Anti-Eviction Mapping Project](https://antievictionmap.com/)  

Washington, DC Maps:
[Mapping Segregation in Washington DC](https://www.mappingsegregationdc.org/) by Prologue DC
[D.C. Music Map](https://folklife.si.edu/dc-music-map) by Smithsonian Center for Folklike & Cultural Heritage

**Comment by rudietuesdays** [comment]
updated along with #24, please close if good @jennwlow !

**Comment by jennwlow** [comment]
I noticed that the "Washington, DC Maps" in links are combined in a single line, is that intentional for legibility or can it be stacked like the other links?

Also, "Folklike" should be "Folklife" -- sorry about that! That was me.

![Screen Shot 2020-12-23 at 12 03 53 PM](https://user-images.githubusercontent.com/75499962/103020763-0677a200-4517-11eb-94bf-9a397c2924e5.png)

**Comment by rudietuesdays** [comment]
Whoops, that spacing was my mistake! Fixed now, along with the typo :)

**Comment by jennwlow** [comment]
Awesome!
