### ISSUE TITLE
Homepage : Project acknowledgements section

### ISSUE THREAD

**Issue by mlewinsmith** [throneless-tech/dear-chinatown#28]
Please constrain the "project acknowledgements" content to the same content well as the accordion content so to remove risk of it overlapping with the card promos.

[Design](https://www.figma.com/file/Gb7be2jpCDFQrdtjXmPqVs/DearChinatownDC?node-id=175%3A203)
<img width="401" alt="Screen Shot 2020-12-31 at 5 20 36 PM" src="https://user-images.githubusercontent.com/43754583/103427102-855e8180-4b8c-11eb-8b43-7b938f1fbe66.png">

[Frontend](https://dear-chinatown.netlify.app/)
<img width="1272" alt="Screen Shot 2020-12-31 at 5 20 00 PM" src="https://user-images.githubusercontent.com/43754583/103427095-737cde80-4b8c-11eb-9003-dade37d9cb8a.png">

**Comment by rudietuesdays** [comment]
@mlewinsmith wanted to check in on this -- the way the page is set up, the card promos can't overlap with the "Project Acknowledgements" section. Happy to shrink the width, I just wanted to make sure it's a style choice and not a concern about overlapping elements that won't occur!

**Comment by mlewinsmith** [comment]
@rudietuesdays yes it's a style choice! The way you have it rn looks great. 

Yes please reduce the width a little bit so this section matches the content well of the accordion.

**Comment by rudietuesdays** [comment]
Thanks for clarifying @mlewinsmith ! Updated :)

**Comment by mlewinsmith** [comment]
@rudietuesdays thank you! Looks good, closing 🌻
