### ISSUE TITLE
Landing Pages : Banner style

### ISSUE THREAD

**Issue by mlewinsmith** [throneless-tech/dear-chinatown#29]
Please add:
- This border underneath page titles
- 80px between title and border
- 120px between border and page content

[Design](https://www.figma.com/file/Gb7be2jpCDFQrdtjXmPqVs/DearChinatownDC?node-id=175%3A203)
<img width="1391" alt="Screen Shot 2020-12-31 at 5 27 50 PM" src="https://user-images.githubusercontent.com/43754583/103427254-c1dead00-4b8d-11eb-8b41-950edd393c5d.png">

Mobile style:
<img width="249" alt="Screen Shot 2020-12-31 at 5 58 09 PM" src="https://user-images.githubusercontent.com/43754583/103430410-c7d68d00-4b91-11eb-8453-ab7a75ba9a40.png">

[Image](https://drive.google.com/file/d/10x2pe6AE17lN9OvpuCRHGdLP_6N24WxV/view?usp=sharing)
![dearchinatown_wahluck_balcony_medjade_invert](https://user-images.githubusercontent.com/43754583/103427274-e5095c80-4b8d-11eb-98e7-8284cf00a84a.jpg)

**Comment by rudietuesdays** [comment]
updated, please close if good @mlewinsmith !

**Comment by mlewinsmith** [comment]
@rudietuesdays this looks great thank you! Closing 🌻
