### ISSUE TITLE
VQA : Homepage : header

### ISSUE THREAD

**Issue by mlewinsmith** [throneless-tech/dear-chinatown#30]
Please adjust the spacing before and after the introductory text. I messed around in chrome inspect and think this looks about right:
- Please move the background image down by 200px
- Please move all of the homepage content down by 20px

Design
<img width="1350" alt="Screen Shot 2020-12-31 at 5 32 46 PM" src="https://user-images.githubusercontent.com/43754583/103427325-4af5e400-4b8e-11eb-816f-2ab24cf9bda8.png">

[Frontend](https://dear-chinatown.netlify.app/)
<img width="1398" alt="Screen Shot 2020-12-31 at 5 33 55 PM" src="https://user-images.githubusercontent.com/43754583/103427334-5f39e100-4b8e-11eb-8dac-4d5128c78a6d.png">

**Comment by rudietuesdays** [comment]
@mlewinsmith It's been a bit tricky to play around with this at different screen sizes, but I did some playing around and lmk how it looks or if it needs more work!

**Comment by mlewinsmith** [comment]
@rudietuesdays I like your boxy solution, I think this works thank you! closing
