### ISSUE TITLE
VQA : Dear Chinatown logo blurry throughout

### ISSUE THREAD

**Issue by mlewinsmith** [throneless-tech/dear-chinatown#32]
Hi! Here's an svg version of the logo to replace the one that is currently in the navigation and the one in the footer. I'm not sure what's easier for you to use, so here's a black, red, and white version: 

Drive link: https://drive.google.com/drive/folders/1JjbkVJYnz6Y_sGxHdkS5ggah1dIa90r0?usp=sharing

**Comment by rudietuesdays** [comment]
updated, please close if good @mlewinsmith !

**Comment by mlewinsmith** [comment]
@rudietuesdays yes looks great! Closing 🌻
