### ISSUE TITLE
VQA : Footer

### ISSUE THREAD

**Issue by mlewinsmith** [throneless-tech/dear-chinatown#33]
Hello! 
- Please left align the Dear Chinatown logo with the text. It looks just slightly off at the moment. 
- Please add the border image to the top of the footer. It seems to appear on the homepage but not on interior pages. 

[Design](https://www.figma.com/file/Gb7be2jpCDFQrdtjXmPqVs/DearChinatownDC?node-id=175%3A203)
<img width="684" alt="Screen Shot 2020-12-31 at 6 11 02 PM" src="https://user-images.githubusercontent.com/43754583/103430589-ab3b5480-4b93-11eb-9799-920cd16de231.png">

Mobile:
<img width="368" alt="Screen Shot 2020-12-31 at 6 10 31 PM" src="https://user-images.githubusercontent.com/43754583/103430588-aaa2be00-4b93-11eb-8fc3-2e5352a2c617.png">

[Frontend](https://dear-chinatown.netlify.app/map/)
<img width="1394" alt="Screen Shot 2020-12-31 at 6 12 38 PM" src="https://user-images.githubusercontent.com/43754583/103430600-ca39e680-4b93-11eb-8934-ead9dd0da021.png">

**Comment by rudietuesdays** [comment]
I *think* all these have been updated via other fixes, but lmk if you're still seeing the issues @mlewinsmith !

**Comment by mlewinsmith** [comment]
@rudietuesdays looks beautiful! closing 🌻
