### ISSUE TITLE
Map page: add 2 more legend colors

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#34]
Add color code for "Residential" and "Religion" categories. 

(No new color for "social network," as we will consolidate this category with "Media Institution" and rename it "Art, Culture and Media".)

<img width="1279" alt="Screen Shot 2021-01-03 at 7 58 56 PM" src="https://user-images.githubusercontent.com/75499962/103493411-2bb1bd80-4dff-11eb-9a09-acc38de410cd.png">

**Comment by rudietuesdays** [comment]
@mlewinsmith I think this one's for you!

**Comment by mlewinsmith** [comment]
Thank you! Let's do:

- Residential: #6794B4 (blue)
- Religion: #8A2E8C (purple)

<img width="403" alt="Screen Shot 2021-01-10 at 1 00 26 PM" src="https://user-images.githubusercontent.com/43754583/104131363-e253f780-5343-11eb-9403-44f7a32fb805.png">

@rudietuesdays

**Comment by rudietuesdays** [comment]
@mlewinsmith added! Lmk if it looks good

**Comment by mlewinsmith** [comment]
Looks good to me @rudietuesdays thank you! @jennwlow does this work?

**Comment by jennwlow** [comment]
Looks great! Thank you @rudietuesdays and @mlewinsmith
