### ISSUE TITLE
Do I need to place the images into Airtable?

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#35]
@rudietuesdays I noticed there's a column in the Airtable for images -- do you want me to migrate the image links from the google spreadsheet into Airtable?

**Comment by rudietuesdays** [comment]
@jennwlow echoing the email exchange, yes please do! 

Please migrate any date to the AirTable that you'd like to show on the site. That includes any data from the Google spreadsheet that may be missing in the AirTable. The AirTable is currently expecting an image file for images; let me know if you'd like it set up a different way! And if you have any trouble or confusion with it, please let me know.

**Comment by jennwlow** [comment]
Got it, I just added photos and poster images to the Airtable. I didn't see them automatically show up in the website so let me know if it's integrated into the airtable as you need it to be.

**Comment by rudietuesdays** [comment]
Thank you! Just got your email and pushed a fix for this bug -- it should show up on the site in a minute or two.

**Comment by jennwlow** [comment]
Yay! Pictures showed up. Can we remove the reload image icon for those markers that don't have an image associated with it? See below:
![Screen Shot 2021-01-30 at 2 18 55 PM](https://user-images.githubusercontent.com/75499962/106365834-1ea4c300-6306-11eb-94e3-abbc2ca3a5b2.png)

**Comment by rudietuesdays** [comment]
@jennwlow oops, thanks for catching! Just pushed a fix, should be up in a minute.
