### ISSUE TITLE
Right edge of photos and menu -- stops expanding with background

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#5]
When I expand my window, the background continues to stretch but the accordion, photos, and menu bar stops at a certain point along the right edge. Is this fixable?

**Comment by rudietuesdays** [comment]
I think I added a fix for this -- @jennwlow could you send a screenshot if it's still looking wonky?

I think what was happening here is the content wasn't staying centered after hitting its maximum width, but let me know if that is off base!
