### ISSUE TITLE
Add 1882 Foundation logo

### ISSUE THREAD

**Issue by jennwlow** [throneless-tech/dear-chinatown#7]
https://drive.google.com/file/d/1wlLLmk9KygvqQCRdcrjxcks1XqFNeo_v/view?usp=sharing

**Comment by rudietuesdays** [comment]
Both sponsor logos are now added in (see issue #6) as well. Let me know what you think!

One I thing I noticed is now visually it's a little redundant, since both sponsor's logos are their names. I wonder if we want to change or remove the text for the links? Curious your thoughts @jennwlow and @mlewinsmith

**Comment by jennwlow** [comment]
I agree. I think the text for the links can be removed and the links can be placed directly on the logos and the logos can be made slightly bigger to take up that space. Also, is the red AARP hard on the eyes against the green? I have a white version, if  you think that's better.

**Comment by rudietuesdays** [comment]
Yes, please send the white version! I agree, I think that'll be much easier to read on the green and will be better especially if we're removing the text links. 

Otherwise, this sounds good! I'll update the image hover styles so it'll be obvious the images are links.

**Comment by rudietuesdays** [comment]
Also, can you send the links that each should go to?

**Comment by jennwlow** [comment]
For sure:
1882 Foundation: www.1882foundation.org
AARP: https://www.aarp.org/livable-communities/community-challenge/ 

(Just pasted the white logo in here, it's probably invisible in the preview, lol.)

![AARP Logo 2020_White](https://user-images.githubusercontent.com/75499962/103020523-8b15f080-4516-11eb-8e32-8312d5026f2c.png)

**Comment by rudietuesdays** [comment]
Perfect, thank you! Now updated
